import { useState, useEffect, useMemo, useRef } from 'react';
import ReactMarkdown from 'react-markdown';
import { 
  Briefcase, Sparkles, FileText, Download, Printer, CheckCircle2, 
  Clock, AlertTriangle, Search, Filter, Plus, RefreshCw, Edit3, 
  Save, X, Volume2, Copy, Check, ChevronRight, FileCheck, 
  ShieldCheck, AlertCircle, ArrowUpRight, BookOpen, Layers,
  Maximize2, Eye, ExternalLink, Send
} from 'lucide-react';
import { getAuthToken } from '../lib/firebase';
import { exportToWord, exportToPrintablePdf } from '../utils/exportDocument';
import { copyToClipboard } from '../utils/clipboard';

export interface TaskItem {
  id: number;
  orgId: number;
  sessionId?: number | null;
  title: string;
  description?: string;
  assignee?: string;
  status: 'PENDING' | 'IN_PROGRESS' | 'COMPLETED';
  deliverable?: string | null;
  deliverableType?: 'PROCEDURE_MANUAL' | 'POLICY' | 'REPORT' | 'CHECKLIST' | 'PLAN' | 'MEETING_MINUTES' | 'DECISION_DRAFT' | string;
  dueDate?: string | null;
  priority?: 'URGENT' | 'HIGH' | 'MEDIUM' | 'LOW';
  createdAt?: string;
}

interface AITasksManagerProps {
  token: string | null;
  userId?: string;
  onAnnounceTask?: (taskTitle: string) => void;
  onTaskDeliverableCreated?: (taskTitle: string) => void;
}

const DELIVERABLE_PRESETS = [
  {
    type: 'PROCEDURE_MANUAL',
    label: '📘 دليل إجراءات تشغيلي (SOP)',
    placeholderTitle: 'دليل إجراءات فحص الشكاوى والتفتيش الميداني',
    defaultDesc: 'وضع إجراءات قياسية موحدة لتوثيق ومعالجة وتدقيق الشكاوى والعمليات الرقابية في المؤسسة.'
  },
  {
    type: 'POLICY',
    label: '⚖️ لائحة وسياسة حوكمة رقابية',
    placeholderTitle: 'لائحة الرقابة الداخلية وحماية المال العام',
    defaultDesc: 'صياغة سياسة شاملة للحوكمة وتفادي تضارب المصالح وضبط الصرفيات والمناقصات.'
  },
  {
    type: 'REPORT',
    label: '📊 تقرير فحص وتدقيق مالي وإداري',
    placeholderTitle: 'تقرير تدقيق المخالفات المالية ونسب الاسترداد',
    defaultDesc: 'حصر مبالغ الهدر وتحديد المسؤوليات والإجراءات التصحيحية وخطط الاسترداد.'
  },
  {
    type: 'CHECKLIST',
    label: '✅ استمارة وقائمة تدقيق ميداني',
    placeholderTitle: 'استمارة التفتيش والرقابة على العقود والتوريدات',
    defaultDesc: 'قائمة تحقق إجرائية للمفتشين الميدانيين أثناء زيارة ومطابقة المواقع.'
  },
  {
    type: 'PLAN',
    label: '📅 خطة عمل تنفيذية ومصفوفة متابعة',
    placeholderTitle: 'الخطة الرقابية الربع سنوية لإغلاق الملاحظات',
    defaultDesc: 'خطة زمنية مرحلية لتنفيذ توصيات لجان الرقابة ومتابعة مؤشرات الإنجاز.'
  },
  {
    type: 'MEETING_MINUTES',
    label: '📝 محضر اجتماع رسمي',
    placeholderTitle: 'محضر اجتماع استعراض ومناقشة الملاحظات',
    defaultDesc: 'صياغة محضر اجتماع تفصيلي يتضمن المداولات، والقرارات المتخذة، والمهام والتكليفات المسندة للأعضاء.'
  },
  {
    type: 'DECISION_DRAFT',
    label: '📜 مسودة قرار تنفيذي',
    placeholderTitle: 'مسودة قرار بتشكيل لجنة تفتيش',
    defaultDesc: 'إعداد ديباجة ومواد لقرار تنفيذي، شاملة المسوغات القانونية ونطاق التطبيق.'
  }
];

export default function AITasksManager({
  token,
  userId,
  onAnnounceTask,
  onTaskDeliverableCreated
}: AITasksManagerProps) {
  const [tasks, setTasks] = useState<TaskItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedTask, setSelectedTask] = useState<TaskItem | null>(null);
  const [activeFilter, setActiveFilter] = useState<'AI_DELIVERABLES' | 'ALL' | 'PENDING' | 'COMPLETED'>('AI_DELIVERABLES');
  const [searchQuery, setSearchQuery] = useState('');
  
  // New task modal state
  const [showNewTaskModal, setShowNewTaskModal] = useState(false);
  const [isSubmittingTask, setIsSubmittingTask] = useState(false);
  const [newTitle, setNewTitle] = useState('');
  const [newDesc, setNewDesc] = useState('');
  const [newType, setNewType] = useState('PROCEDURE_MANUAL');
  const [newDueDate, setNewDueDate] = useState('');
  const [newPriority, setNewPriority] = useState<'URGENT' | 'HIGH' | 'MEDIUM'>('HIGH');
  const [newAssignee, setNewAssignee] = useState('الذكاء الاصطناعي (المستشار الرقابي)');
  const [autoGenerateDeliverable, setAutoGenerateDeliverable] = useState(true);
  const [customPromptGuidance, setCustomPromptGuidance] = useState('');

  // Deliverable Editor & AI Prompting
  const [isEditingDeliverable, setIsEditingDeliverable] = useState(false);
  const [editedContent, setEditedContent] = useState('');
  const [isGeneratingAi, setIsGeneratingAi] = useState(false);
  const [aiPromptInstruction, setAiPromptInstruction] = useState('');
  const [copiedId, setCopiedId] = useState<number | null>(null);
  
  // Dedicated Full-Screen Document Preview Modal
  const [showPreviewModal, setShowPreviewModal] = useState(false);
  const viewerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    fetchTasks();
  }, [token]);

  const fetchTasks = async () => {
    try {
      setLoading(true);
      const activeToken = token || await getAuthToken();
      if (!activeToken) {
        setLoading(false);
        return;
      }
      const res = await fetch('/api/tasks', {
        headers: { Authorization: `Bearer ${activeToken}` }
      });
      if (res.ok) {
        const data = await res.json();
        setTasks(data || []);
        // Auto-select first AI deliverable if none selected
        if (!selectedTask && data && data.length > 0) {
          const firstWithDeliverable = data.find((t: any) => !!t.deliverable) || data[0];
          setSelectedTask(firstWithDeliverable);
          setEditedContent(firstWithDeliverable.deliverable || '');
        }
      }
    } catch (e) {
      console.error('Error fetching tasks:', e);
    } finally {
      setLoading(false);
    }
  };

  // Filtered tasks
  const filteredTasks = useMemo(() => {
    return tasks.filter(t => {
      const matchesSearch = !searchQuery || 
        t.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        (t.description && t.description.toLowerCase().includes(searchQuery.toLowerCase())) ||
        (t.assignee && t.assignee.toLowerCase().includes(searchQuery.toLowerCase()));

      if (!matchesSearch) return false;

      if (activeFilter === 'AI_DELIVERABLES') {
        return !!t.deliverable || (t.assignee && (t.assignee.includes('ذكاء') || t.assignee.toLowerCase().includes('ai')));
      }
      if (activeFilter === 'PENDING') {
        return t.status !== 'COMPLETED';
      }
      if (activeFilter === 'COMPLETED') {
        return t.status === 'COMPLETED';
      }
      return true;
    });
  }, [tasks, activeFilter, searchQuery]);

  // Statistics
  const aiDeliverablesCount = tasks.filter(t => !!t.deliverable).length;
  const pendingCount = tasks.filter(t => t.status !== 'COMPLETED').length;
  const completedCount = tasks.filter(t => t.status === 'COMPLETED').length;

  const handleSelectTask = (task: TaskItem) => {
    setSelectedTask(task);
    setEditedContent(task.deliverable || '');
    setIsEditingDeliverable(false);
  };

  const openDocumentPreview = (task: TaskItem) => {
    setSelectedTask(task);
    setEditedContent(task.deliverable || '');
    setIsEditingDeliverable(false);
    setShowPreviewModal(true);
    // Also scroll down to viewer on mobile / small screen layouts
    setTimeout(() => {
      viewerRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }, 100);
  };

  // Create new task and auto-generate deliverable
  const handleCreateTask = async (e: React.FormEvent) => {
    e.preventDefault();
    const activeToken = token || await getAuthToken();
    if (!newTitle.trim() || !activeToken) return;

    setIsSubmittingTask(true);
    try {
      const res = await fetch('/api/tasks', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${activeToken}`
        },
        body: JSON.stringify({
          title: newTitle.trim(),
          description: newDesc.trim(),
          deliverableType: newType,
          dueDate: newDueDate || null,
          priority: newPriority,
          assignee: newAssignee,
          generateDeliverable: autoGenerateDeliverable,
          customInstructions: customPromptGuidance
        })
      });

      if (res.ok) {
        const createdTask = await res.json();
        setTasks(prev => [createdTask, ...prev]);
        setSelectedTask(createdTask);
        setEditedContent(createdTask.deliverable || '');
        setShowNewTaskModal(false);
        resetForm();

        if (createdTask.deliverable && onTaskDeliverableCreated) {
          onTaskDeliverableCreated(createdTask.title);
        }
      }
    } catch (err) {
      console.error('Error creating task:', err);
    } finally {
      setIsSubmittingTask(false);
    }
  };

  const resetForm = () => {
    setNewTitle('');
    setNewDesc('');
    setNewType('PROCEDURE_MANUAL');
    setNewDueDate('');
    setNewPriority('HIGH');
    setCustomPromptGuidance('');
  };

  // Save manually edited deliverable
  const handleSaveEditedDeliverable = async () => {
    const activeToken = token || await getAuthToken();
    if (!selectedTask || !activeToken) return;
    try {
      const res = await fetch(`/api/tasks/${selectedTask.id}`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${activeToken}`
        },
        body: JSON.stringify({
          deliverable: editedContent
        })
      });

      if (res.ok) {
        const updated = await res.json();
        setSelectedTask(prev => prev ? { ...prev, deliverable: editedContent } : null);
        setTasks(prev => prev.map(t => t.id === selectedTask.id ? { ...t, deliverable: editedContent } : t));
        setIsEditingDeliverable(false);
      }
    } catch (err) {
      console.error('Error saving deliverable:', err);
    }
  };

  // Trigger AI to generate or enhance deliverable
  const handleEnhanceWithAI = async () => {
    const activeToken = token || await getAuthToken();
    if (!selectedTask || !activeToken) return;
    setIsGeneratingAi(true);

    try {
      const res = await fetch(`/api/tasks/${selectedTask.id}/generate-deliverable`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${activeToken}`
        },
        body: JSON.stringify({
          customInstructions: aiPromptInstruction || 'إعادة صياغة وتوسيع الدليل بأسلوب رقابي رصين وتحديث مصفوفة الصلاحيات والاستمارات',
          deliverableType: selectedTask.deliverableType || 'PROCEDURE_MANUAL'
        })
      });

      if (res.ok) {
        const data = await res.json();
        if (data.task) {
          setSelectedTask(data.task);
          setEditedContent(data.task.deliverable || '');
          setTasks(prev => prev.map(t => t.id === selectedTask.id ? data.task : t));
          setAiPromptInstruction('');
          if (onTaskDeliverableCreated) {
            onTaskDeliverableCreated(data.task.title);
          }
        }
      }
    } catch (err) {
      console.error('Error enhancing with AI:', err);
    } finally {
      setIsGeneratingAi(false);
    }
  };

  // Toggle completion status
  const handleToggleStatus = async (taskId: number, currentStatus: string) => {
    const activeToken = token || await getAuthToken();
    if (!activeToken) return;
    const nextStatus = currentStatus === 'COMPLETED' ? 'PENDING' : 'COMPLETED';

    try {
      setTasks(prev => prev.map(t => t.id === taskId ? { ...t, status: nextStatus } : t));
      if (selectedTask && selectedTask.id === taskId) {
        setSelectedTask(prev => prev ? { ...prev, status: nextStatus } : null);
      }

      await fetch(`/api/tasks/${taskId}`, {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${activeToken}`
        },
        body: JSON.stringify({ status: nextStatus })
      });
    } catch (e) {
      console.error('Error toggling status:', e);
    }
  };

  const handleCopyContent = async (content: string, id: number) => {
    await copyToClipboard(content);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2500);
  };

  const handleWordExport = (task: TaskItem) => {
    if (!task.deliverable) return;
    exportToWord({
      title: task.title,
      content: task.deliverable,
      deliverableType: getDeliverableLabel(task.deliverableType)
    });
  };

  const handlePdfPrintExport = (task: TaskItem) => {
    if (!task.deliverable) return;
    exportToPrintablePdf({
      title: task.title,
      content: task.deliverable,
      deliverableType: getDeliverableLabel(task.deliverableType)
    });
  };

  function getDeliverableLabel(type?: string) {
    switch (type) {
      case 'POLICY': return 'لائحة وسياسة حوكمة';
      case 'REPORT': return 'تقرير تدقيق وفحص';
      case 'CHECKLIST': return 'استمارة تفتيش ميداني';
      case 'PLAN': return 'خطة عمل تنفيذية';
      case 'MEETING_MINUTES': return 'محضر اجتماع رسمي';
      case 'DECISION_DRAFT': return 'مسودة قرار تنفيذي';
      default: return 'دليل إجراءات تشغيلي (SOP)';
    }
  }

  return (
    <div className="w-full max-w-7xl mx-auto p-4 md:p-6 space-y-6 animate-in fade-in duration-300" dir="rtl">
      
      {/* Top Banner & Header */}
      <div className="bg-slate-900 border border-slate-800 p-6 rounded-3xl shadow-xl flex flex-col md:flex-row md:items-center justify-between gap-5">
        <div>
          <div className="flex items-center gap-3 mb-2">
            <div className="w-10 h-10 rounded-2xl bg-blue-600/20 border border-blue-500/30 flex items-center justify-center text-blue-400 shadow-md">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-xl sm:text-2xl font-bold text-white flex items-center gap-2">
                مهام وتكليفات الذكاء الاصطناعي
                <span className="text-xs font-semibold px-2.5 py-0.5 rounded-full bg-blue-500/10 text-blue-400 border border-blue-500/20">
                  {aiDeliverablesCount} مخرج منجز
                </span>
              </h2>
              <p className="text-slate-400 text-xs sm:text-sm">
                متابعة التكليفات الرقابية، توليد أدلة الإجراءات واللوائح والتقارير، والتصدير المباشر بصيغ Word و PDF
              </p>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-wrap items-center gap-3">
          {onAnnounceTask && selectedTask && (
            <button
              onClick={() => onAnnounceTask(selectedTask.title)}
              className="flex items-center gap-2 px-4 py-2.5 bg-amber-600/20 hover:bg-amber-600/30 text-amber-300 border border-amber-500/30 rounded-2xl text-xs font-bold transition-all shadow-md cursor-pointer"
              title="تذكير صوتي فوري بهذه المهمة"
            >
              <Volume2 className="w-4 h-4 text-amber-400" />
              تنبيه صوتي بالمهمة
            </button>
          )}

          <button
            onClick={() => setShowNewTaskModal(true)}
            className="flex items-center gap-2 px-5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white rounded-2xl text-xs font-bold transition-all shadow-lg shadow-blue-600/20 hover:scale-[1.02] cursor-pointer"
          >
            <Plus className="w-4 h-4" />
            تكليف الذكاء بمهمة أو دليل جديد
          </button>
        </div>
      </div>

      {/* KPI Stats Bar */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        <div className="bg-slate-900 border border-slate-800 p-4 rounded-2xl">
          <div className="flex items-center justify-between mb-1">
            <span className="text-xs text-slate-400 font-medium">مخرجات الذكاء المنجزة</span>
            <FileCheck className="w-4 h-4 text-blue-400" />
          </div>
          <p className="text-xl font-bold text-white">{aiDeliverablesCount}</p>
          <span className="text-[11px] text-blue-400">أدلة، لوائح، تقارير جاهزة</span>
        </div>

        <div className="bg-slate-900 border border-slate-800 p-4 rounded-2xl">
          <div className="flex items-center justify-between mb-1">
            <span className="text-xs text-slate-400 font-medium">إجمالي التكليفات</span>
            <Briefcase className="w-4 h-4 text-slate-400" />
          </div>
          <p className="text-xl font-bold text-white">{tasks.length}</p>
          <span className="text-[11px] text-slate-500">مسجلة في النظام</span>
        </div>

        <div className="bg-slate-900 border border-slate-800 p-4 rounded-2xl">
          <div className="flex items-center justify-between mb-1">
            <span className="text-xs text-slate-400 font-medium">مهام قيد المتابعة</span>
            <Clock className="w-4 h-4 text-amber-400" />
          </div>
          <p className="text-xl font-bold text-amber-400">{pendingCount}</p>
          <span className="text-[11px] text-amber-400/80">مطلوب إنجازها</span>
        </div>

        <div className="bg-slate-900 border border-slate-800 p-4 rounded-2xl">
          <div className="flex items-center justify-between mb-1">
            <span className="text-xs text-slate-400 font-medium">التكليفات المكتملة</span>
            <CheckCircle2 className="w-4 h-4 text-emerald-400" />
          </div>
          <p className="text-xl font-bold text-emerald-400">{completedCount}</p>
          <span className="text-[11px] text-emerald-400/80">معتمدة ومنجزة بنجاح</span>
        </div>
      </div>

      {/* Filter Tabs & Search Bar */}
      <div className="flex flex-col sm:flex-row items-center justify-between gap-3 bg-slate-900/60 p-3 rounded-2xl border border-slate-800">
        <div className="flex items-center gap-1.5 overflow-x-auto w-full sm:w-auto pb-1 sm:pb-0">
          <button
            onClick={() => setActiveFilter('AI_DELIVERABLES')}
            className={`px-3.5 py-1.5 rounded-xl text-xs font-bold transition-all whitespace-nowrap cursor-pointer ${
              activeFilter === 'AI_DELIVERABLES' 
                ? 'bg-blue-600 text-white shadow' 
                : 'text-slate-400 hover:text-white hover:bg-slate-800'
            }`}
          >
            🤖 مخرجات وأدلة الذكاء ({aiDeliverablesCount})
          </button>

          <button
            onClick={() => setActiveFilter('ALL')}
            className={`px-3.5 py-1.5 rounded-xl text-xs font-bold transition-all whitespace-nowrap cursor-pointer ${
              activeFilter === 'ALL' 
                ? 'bg-blue-600 text-white shadow' 
                : 'text-slate-400 hover:text-white hover:bg-slate-800'
            }`}
          >
            📋 كافة المهام ({tasks.length})
          </button>

          <button
            onClick={() => setActiveFilter('PENDING')}
            className={`px-3.5 py-1.5 rounded-xl text-xs font-bold transition-all whitespace-nowrap cursor-pointer ${
              activeFilter === 'PENDING' 
                ? 'bg-amber-600 text-white shadow' 
                : 'text-slate-400 hover:text-white hover:bg-slate-800'
            }`}
          >
            ⏳ قيد المتابعة ({pendingCount})
          </button>

          <button
            onClick={() => setActiveFilter('COMPLETED')}
            className={`px-3.5 py-1.5 rounded-xl text-xs font-bold transition-all whitespace-nowrap cursor-pointer ${
              activeFilter === 'COMPLETED' 
                ? 'bg-emerald-600 text-white shadow' 
                : 'text-slate-400 hover:text-white hover:bg-slate-800'
            }`}
          >
            ✅ المكتملة ({completedCount})
          </button>
        </div>

        {/* Search */}
        <div className="relative w-full sm:w-64">
          <Search className="w-3.5 h-3.5 absolute right-3 top-1/2 -translate-y-1/2 text-slate-500" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="بحث في التكليفات والأدلة..."
            className="w-full bg-slate-950 border border-slate-800 rounded-xl pr-9 pl-3 py-1.5 text-xs text-white placeholder-slate-500 outline-none focus:border-blue-500"
          />
        </div>
      </div>

      {/* Main Content Layout: Tasks List + Deliverable Reader */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        
        {/* Left Side: Tasks Cards Column */}
        <div className="lg:col-span-5 space-y-3 max-h-[800px] overflow-y-auto pr-1">
          {loading ? (
            <div className="text-center py-12 text-slate-500 text-xs">
              <RefreshCw className="w-6 h-6 animate-spin text-blue-500 mx-auto mb-2" />
              جاري تحميل قائمة التكليفات والمخرجات...
            </div>
          ) : filteredTasks.length === 0 ? (
            <div className="bg-slate-900 border border-slate-800 rounded-3xl p-8 text-center text-slate-500">
              <BookOpen className="w-10 h-10 mx-auto mb-3 opacity-30 text-blue-400" />
              <p className="text-sm font-semibold text-slate-300 mb-1">لا توجد تكليفات مطابقة</p>
              <p className="text-xs text-slate-500 mb-4">يمكنك إنشاء تكليف جديد وطلب عمل دليل إجراءات أو تقرير فوراً.</p>
              <button
                onClick={() => setShowNewTaskModal(true)}
                className="px-4 py-2 bg-blue-600 text-white rounded-xl text-xs font-bold"
              >
                + إنشاء تكليف جديد
              </button>
            </div>
          ) : (
            filteredTasks.map(task => {
              const isSelected = selectedTask?.id === task.id;
              const hasDeliverable = !!task.deliverable;

              return (
                <div
                  key={task.id}
                  onClick={() => handleSelectTask(task)}
                  className={`p-4 rounded-2xl border transition-all cursor-pointer text-right group ${
                    isSelected 
                      ? 'bg-slate-900 border-blue-500/60 shadow-lg shadow-blue-900/10 ring-1 ring-blue-500/30' 
                      : 'bg-slate-900/80 hover:bg-slate-900 border-slate-800 hover:border-slate-700'
                  }`}
                >
                  <div className="flex items-start justify-between gap-2 mb-2">
                    <div className="flex items-center gap-1.5 flex-wrap">
                      <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full border ${
                        task.priority === 'URGENT' ? 'bg-rose-500/10 text-rose-400 border-rose-500/20' :
                        task.priority === 'HIGH' ? 'bg-amber-500/10 text-amber-400 border-amber-500/20' :
                        'bg-slate-800 text-slate-400 border-slate-700'
                      }`}>
                        {task.priority === 'URGENT' ? 'عاجل جداً' : task.priority === 'HIGH' ? 'أولوية عالية' : 'عادي'}
                      </span>

                      {hasDeliverable && (
                        <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-blue-500/15 text-blue-300 border border-blue-500/30 flex items-center gap-1">
                          <Sparkles className="w-2.5 h-2.5 text-blue-400" />
                          {getDeliverableLabel(task.deliverableType)}
                        </span>
                      )}
                    </div>

                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        handleToggleStatus(task.id, task.status);
                      }}
                      className={`px-2.5 py-1 rounded-lg text-[11px] font-bold border transition-colors flex items-center gap-1 ${
                        task.status === 'COMPLETED'
                          ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30'
                          : 'bg-slate-800 text-slate-400 border-slate-700 hover:text-emerald-400'
                      }`}
                      title="تبديل حالة الإنجاز"
                    >
                      <Check className="w-3 h-3" />
                      {task.status === 'COMPLETED' ? 'مكتمل' : 'قيد التنفيذ'}
                    </button>
                  </div>

                  <h3 className={`font-bold text-sm mb-1.5 leading-snug ${isSelected ? 'text-white' : 'text-slate-200 group-hover:text-white'}`}>
                    {task.title}
                  </h3>

                  {task.description && (
                    <p className="text-xs text-slate-400 line-clamp-2 mb-3 leading-relaxed">
                      {task.description}
                    </p>
                  )}

                  <div className="flex items-center justify-between text-[11px] text-slate-500 pt-2 border-t border-slate-800/80">
                    <span className="flex items-center gap-1 text-slate-400">
                      <span className="w-1.5 h-1.5 rounded-full bg-blue-400" />
                      {task.assignee || 'الذكاء الاصطناعي'}
                    </span>
                    
                    {hasDeliverable ? (
                      <button
                        type="button"
                        onClick={(e) => {
                          e.stopPropagation();
                          openDocumentPreview(task);
                        }}
                        className="px-2.5 py-1 rounded-lg bg-blue-600/20 hover:bg-blue-600/30 text-blue-400 hover:text-blue-300 font-bold flex items-center gap-1 text-[11px] border border-blue-500/30 transition-all shadow-sm"
                      >
                        <Eye className="w-3.5 h-3.5" />
                        استعراض الوثيقة ←
                      </button>
                    ) : (
                      <button
                        type="button"
                        onClick={(e) => {
                          e.stopPropagation();
                          openDocumentPreview(task);
                        }}
                        className="px-2.5 py-1 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 font-medium flex items-center gap-1 text-[11px] border border-slate-700"
                      >
                        <Sparkles className="w-3 h-3 text-blue-400" />
                        توليد بالذكاء
                      </button>
                    )}
                  </div>
                </div>
              );
            })
          )}
        </div>

        {/* Right Side: Selected Deliverable Viewer & Editor */}
        <div ref={viewerRef} className="lg:col-span-7">
          {selectedTask ? (
            <div className="bg-slate-900 border border-slate-800 rounded-3xl overflow-hidden shadow-2xl flex flex-col min-h-[650px]">
              
              {/* Deliverable Header Controls */}
              <div className="p-5 bg-slate-900/90 border-b border-slate-800 flex flex-wrap items-center justify-between gap-3">
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-xs font-bold px-2.5 py-0.5 rounded-full bg-blue-500/10 text-blue-400 border border-blue-500/20">
                      {getDeliverableLabel(selectedTask.deliverableType)}
                    </span>
                    <span className="text-xs text-slate-500">
                      المسؤول: {selectedTask.assignee || 'الذكاء الاصطناعي'}
                    </span>
                  </div>
                  <h3 className="text-base sm:text-lg font-bold text-white leading-snug">
                    {selectedTask.title}
                  </h3>
                </div>

                {/* Export & Action Buttons */}
                <div className="flex items-center gap-2 flex-wrap">
                  {/* Full Modal Viewer Button */}
                  <button
                    onClick={() => setShowPreviewModal(true)}
                    className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-950 hover:bg-blue-900 text-blue-300 rounded-xl text-xs font-bold border border-blue-500/30 transition-all shadow-sm"
                    title="استعراض ملء الشاشة بنافذة مخصصة"
                  >
                    <Maximize2 className="w-3.5 h-3.5" />
                    استعراض مكبر
                  </button>

                  {selectedTask.deliverable && (
                    <>
                      {/* Word Export */}
                      <button
                        onClick={() => handleWordExport(selectedTask)}
                        className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-xs font-bold transition-all shadow-md shadow-blue-600/20 cursor-pointer"
                        title="تحميل كملف Word (.docx) قابل للتعديل"
                      >
                        <Download className="w-3.5 h-3.5" />
                        تصدير Word (.docx)
                      </button>

                      {/* PDF Print Export */}
                      <button
                        onClick={() => handlePdfPrintExport(selectedTask)}
                        className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-xl text-xs font-bold border border-slate-700 transition-all cursor-pointer"
                        title="طباعة أو تصدير بصيغة PDF"
                      >
                        <Printer className="w-3.5 h-3.5 text-blue-400" />
                        طباعة / PDF
                      </button>

                      {/* Copy */}
                      <button
                        onClick={() => handleCopyContent(selectedTask.deliverable!, selectedTask.id)}
                        className="p-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-xl border border-slate-700 transition-colors"
                        title="نسخ محتوى الوثيقة"
                      >
                        {copiedId === selectedTask.id ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                      </button>

                      {/* Edit Toggle */}
                      <button
                        onClick={() => setIsEditingDeliverable(!isEditingDeliverable)}
                        className={`p-2 rounded-xl border transition-colors ${
                          isEditingDeliverable 
                            ? 'bg-amber-500 text-black border-amber-400 font-bold' 
                            : 'bg-slate-800 hover:bg-slate-700 text-slate-300 border-slate-700'
                        }`}
                        title={isEditingDeliverable ? "إلغاء التعديل" : "تعديل نص الوثيقة"}
                      >
                        <Edit3 className="w-3.5 h-3.5" />
                      </button>
                    </>
                  )}

                  {!selectedTask.deliverable && (
                    <button
                      onClick={handleEnhanceWithAI}
                      disabled={isGeneratingAi}
                      className="flex items-center gap-1.5 px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-xs font-bold shadow-lg shadow-blue-600/20 disabled:opacity-50 cursor-pointer"
                    >
                      <Sparkles className="w-3.5 h-3.5" />
                      {isGeneratingAi ? 'جاري الصياغة...' : 'توليد الوثيقة بالذكاء الاصطناعي'}
                    </button>
                  )}
                </div>
              </div>

              {/* Deliverable Body: Formatted View vs Live Editor */}
              <div className="flex-1 p-6 overflow-y-auto max-h-[600px] bg-slate-950/40">
                {isEditingDeliverable ? (
                  <div className="space-y-4 h-full flex flex-col">
                    <div className="flex items-center justify-between pb-2 border-b border-slate-800 text-xs text-slate-400">
                      <span>محرر نصوص الوثيقة المباشر (Markdown):</span>
                      <button
                        onClick={handleSaveEditedDeliverable}
                        className="px-4 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl font-bold flex items-center gap-1.5 text-xs shadow-md"
                      >
                        <Save className="w-3.5 h-3.5" /> حفظ التعديلات
                      </button>
                    </div>
                    <textarea
                      value={editedContent}
                      onChange={(e) => setEditedContent(e.target.value)}
                      rows={18}
                      className="w-full flex-1 bg-slate-900 border border-slate-700 rounded-2xl p-4 text-white text-xs sm:text-sm font-mono leading-relaxed outline-none focus:border-blue-500 resize-none"
                    />
                  </div>
                ) : selectedTask.deliverable ? (
                  <div className="prose prose-invert max-w-none text-xs sm:text-sm leading-relaxed space-y-4">
                    <ReactMarkdown>{selectedTask.deliverable}</ReactMarkdown>
                  </div>
                ) : (
                  <div className="py-20 text-center flex flex-col items-center justify-center text-slate-500">
                    <div className="w-14 h-14 rounded-2xl bg-blue-600/10 border border-blue-500/20 flex items-center justify-center text-blue-400 mb-4">
                      <Sparkles className="w-7 h-7" />
                    </div>
                    <h4 className="text-base font-bold text-white mb-1">لم يتم توليد وثيقة هذا التكليف بعد</h4>
                    <p className="text-xs text-slate-400 max-w-md mb-6 leading-relaxed">
                      اضغط على الزر أدناه ليقوم المستشار الرقابي الذكي بصياغة دليل إجراءات أو وثيقة رسمية متكاملة وجاهزة للتصدير كملف Word أو PDF.
                    </p>
                    <button
                      onClick={handleEnhanceWithAI}
                      disabled={isGeneratingAi}
                      className="px-6 py-3 bg-blue-600 hover:bg-blue-500 text-white rounded-2xl text-xs font-bold shadow-xl shadow-blue-600/20 flex items-center gap-2 disabled:opacity-50 cursor-pointer"
                    >
                      <Sparkles className="w-4 h-4" />
                      {isGeneratingAi ? 'جاري إعداد وصياغة الدليل...' : 'توليد وإنجاز الدليل فوراً بالذكاء الاصطناعي'}
                    </button>
                  </div>
                )}
              </div>

              {/* Bottom AI Prompt Enhancer Bar */}
              {selectedTask.deliverable && (
                <div className="p-3.5 bg-slate-900 border-t border-slate-800 flex items-center gap-2">
                  <div className="p-2 rounded-xl bg-blue-600/20 text-blue-400 shrink-0">
                    <Sparkles className="w-4 h-4" />
                  </div>
                  <input
                    type="text"
                    value={aiPromptInstruction}
                    onChange={(e) => setAiPromptInstruction(e.target.value)}
                    onKeyDown={(e) => e.key === 'Enter' && handleEnhanceWithAI()}
                    placeholder="اطلب من الذكاء تعديل أو إضافة قسم (مثال: أضف نموذج استمارة تفتيش، وسّع جدول الصلاحيات)..."
                    className="flex-1 bg-slate-950 border border-slate-800 rounded-xl px-3.5 py-2 text-xs text-white placeholder-slate-500 outline-none focus:border-blue-500"
                  />
                  <button
                    onClick={handleEnhanceWithAI}
                    disabled={isGeneratingAi}
                    className="px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-xs font-bold transition-all shadow-md shadow-blue-600/20 disabled:opacity-50 whitespace-nowrap cursor-pointer"
                  >
                    {isGeneratingAi ? 'جاري التحديث...' : 'تطوير بالذكاء'}
                  </button>
                </div>
              )}

            </div>
          ) : (
            <div className="bg-slate-900 border border-slate-800 rounded-3xl p-16 text-center text-slate-500 flex flex-col items-center justify-center min-h-[500px]">
              <Layers className="w-12 h-12 mb-3 opacity-20 text-blue-400" />
              <p className="text-sm font-semibold text-slate-300">حدد تكليفاً من القائمة الجانبية</p>
              <p className="text-xs text-slate-500 mt-1">لاستعراض وثيقة الإنجاز الكاملة أو تصديرها كملف Word أو PDF.</p>
            </div>
          )}
        </div>

      </div>

      {/* New Task & AI Deliverable Modal */}
      {showNewTaskModal && (
        <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4 backdrop-blur-sm">
          <div className="bg-slate-900 border border-slate-700 rounded-3xl w-full max-w-2xl shadow-2xl overflow-hidden max-h-[90vh] overflow-y-auto">
            
            <div className="bg-gradient-to-r from-blue-950/60 to-slate-900 p-6 border-b border-blue-900/30 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-2xl bg-blue-900/50 border border-blue-500/30 flex items-center justify-center text-blue-400">
                  <Sparkles className="w-6 h-6" />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-white">تكليف الذكاء الاصطناعي بمهمة أو دليل جديد</h3>
                  <p className="text-xs text-blue-400/80 mt-0.5">سيقوم الذكاء بإنجاز الوثيقة فوراً وتوفيرها للتحميل كـ Word و PDF</p>
                </div>
              </div>
              <button onClick={() => setShowNewTaskModal(false)} className="text-slate-400 hover:text-white text-sm">
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleCreateTask} className="p-6 space-y-4">
              
              {/* Presets Row */}
              <div>
                <label className="block text-xs font-bold text-slate-300 mb-2">نماذج مخرجات سريعة جاهزة:</label>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                  {DELIVERABLE_PRESETS.map((preset, idx) => (
                    <button
                      key={idx}
                      type="button"
                      onClick={() => {
                        setNewType(preset.type);
                        setNewTitle(preset.placeholderTitle);
                        setNewDesc(preset.defaultDesc);
                      }}
                      className={`text-right p-2.5 rounded-xl border text-xs transition-all flex flex-col justify-between ${
                        newType === preset.type && newTitle === preset.placeholderTitle
                          ? 'bg-blue-600/20 border-blue-500 text-white font-bold'
                          : 'bg-slate-800/60 hover:bg-slate-800 border-slate-700 text-slate-300'
                      }`}
                    >
                      <span className="font-semibold text-[11px] mb-1">{preset.label}</span>
                      <span className="text-[10px] text-slate-400 truncate">{preset.placeholderTitle}</span>
                    </button>
                  ))}
                </div>
              </div>

              {/* Title */}
              <div>
                <label className="block text-xs font-bold text-slate-300 mb-1.5">
                  عنوان التكليف / المخرج المطلوب <span className="text-red-400">*</span>
                </label>
                <input
                  type="text"
                  required
                  value={newTitle}
                  onChange={(e) => setNewTitle(e.target.value)}
                  placeholder="مثال: عمل دليل إجراءات التفتيش الميداني على الشكاوى..."
                  className="w-full px-4 py-2.5 rounded-xl bg-slate-800 border border-slate-700 text-white text-xs focus:ring-2 focus:ring-blue-500 outline-none"
                />
              </div>

              {/* Type and Priority */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-bold text-slate-300 mb-1.5">نوع الوثيقة والمخرج</label>
                  <select
                    value={newType}
                    onChange={(e) => setNewType(e.target.value)}
                    className="w-full px-3.5 py-2.5 rounded-xl bg-slate-800 border border-slate-700 text-white text-xs outline-none"
                  >
                    <option value="PROCEDURE_MANUAL">📘 دليل إجراءات تشغيلي (SOP)</option>
                    <option value="POLICY">⚖️ لائحة وسياسة حوكمة</option>
                    <option value="REPORT">📊 تقرير فحص وتدقيق مالي/إداري</option>
                    <option value="CHECKLIST">✅ استمارة وقائمة تدقيق ميداني</option>
                    <option value="PLAN">📅 خطة عمل تنفيذية زمنية</option>
                    <option value="MEETING_MINUTES">📝 محضر اجتماع رسمي</option>
                    <option value="DECISION_DRAFT">📜 مسودة قرار تنفيذي</option>
                  </select>
                </div>

                <div>
                  <label className="block text-xs font-bold text-slate-300 mb-1.5">مستوى الأولوية</label>
                  <select
                    value={newPriority}
                    onChange={(e) => setNewPriority(e.target.value as any)}
                    className="w-full px-3.5 py-2.5 rounded-xl bg-slate-800 border border-slate-700 text-white text-xs outline-none"
                  >
                    <option value="URGENT">🔴 عاجل وفوري</option>
                    <option value="HIGH">🟠 أولوية عالية</option>
                    <option value="MEDIUM">🟡 أولوية متوسطة</option>
                  </select>
                </div>
              </div>

              {/* Description */}
              <div>
                <label className="block text-xs font-bold text-slate-300 mb-1.5">
                  تفاصيل النطاق والمعايير المستهدفة
                </label>
                <textarea
                  value={newDesc}
                  onChange={(e) => setNewDesc(e.target.value)}
                  rows={3}
                  placeholder="حدد نطاق الدليل والجهات المشمولة واللوائح الواجب الاستناد عليها..."
                  className="w-full px-4 py-2.5 rounded-xl bg-slate-800 border border-slate-700 text-white text-xs outline-none resize-none leading-relaxed"
                />
              </div>

              {/* Auto Generate Toggle */}
              <div className="p-3.5 rounded-2xl bg-blue-950/30 border border-blue-500/30 flex items-center justify-between">
                <div>
                  <h4 className="text-xs font-bold text-white flex items-center gap-1.5">
                    <Sparkles className="w-4 h-4 text-blue-400" />
                    إنجاز وتوليد الوثيقة بالذكاء فوراً
                  </h4>
                  <p className="text-[11px] text-blue-300/80 mt-0.5">
                    سيقوم النظام بصياغة المحتوى الكامل وتجهيز ملف Word و PDF تلقائياً
                  </p>
                </div>
                <input
                  type="checkbox"
                  checked={autoGenerateDeliverable}
                  onChange={(e) => setAutoGenerateDeliverable(e.target.checked)}
                  className="w-5 h-5 rounded text-blue-600 focus:ring-blue-500 bg-slate-800 border-slate-700 cursor-pointer"
                />
              </div>

              {/* Modal Actions */}
              <div className="pt-3 border-t border-slate-800 flex justify-end gap-3">
                <button
                  type="button"
                  onClick={() => setShowNewTaskModal(false)}
                  className="px-4 py-2.5 rounded-xl border border-slate-700 text-slate-300 text-xs font-semibold hover:bg-slate-800"
                >
                  إلغاء
                </button>

                <button
                  type="submit"
                  disabled={isSubmittingTask || !newTitle.trim()}
                  className="px-6 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold transition-all shadow-lg shadow-blue-600/20 flex items-center gap-2 disabled:opacity-50 cursor-pointer"
                >
                  {isSubmittingTask ? (
                    <>
                      <RefreshCw className="w-4 h-4 animate-spin" />
                      جاري صياغة وإنجاز الوثيقة...
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-4 h-4" />
                      اعتماد التكليف وتوليد الإنجاز
                    </>
                  )}
                </button>
              </div>

            </form>
          </div>
        </div>
      )}

      {/* Full-Screen Document Preview & Action Modal (Always pops up in front with z-[100]) */}
      {showPreviewModal && selectedTask && (
        <div 
          className="fixed inset-0 z-[100] flex items-center justify-center p-2 sm:p-4 md:p-6 bg-black/85 backdrop-blur-md animate-in fade-in duration-200"
          dir="rtl"
          onClick={() => setShowPreviewModal(false)}
        >
          <div 
            className="bg-slate-900 border border-slate-700 w-full max-w-5xl max-h-[92vh] rounded-3xl flex flex-col shadow-2xl overflow-hidden animate-in zoom-in-95 duration-150"
            onClick={(e) => e.stopPropagation()}
          >
            
            {/* Modal Header */}
            <div className="p-4 sm:p-5 bg-gradient-to-r from-slate-900 via-blue-950/40 to-slate-900 border-b border-slate-700/80 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
              <div className="flex items-center gap-3">
                <div className="p-2.5 bg-blue-600/20 text-blue-400 border border-blue-500/30 rounded-2xl shrink-0">
                  <FileText className="w-6 h-6" />
                </div>
                <div>
                  <div className="flex items-center gap-2 flex-wrap mb-1">
                    <span className="text-[11px] font-bold px-2.5 py-0.5 rounded-full bg-blue-500/15 text-blue-300 border border-blue-500/30">
                      {getDeliverableLabel(selectedTask.deliverableType)}
                    </span>
                    <span className="text-[11px] text-slate-400">
                      المسؤول: <strong className="text-slate-200">{selectedTask.assignee || 'الذكاء الاصطناعي'}</strong>
                    </span>
                    <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full border ${
                      selectedTask.priority === 'URGENT' ? 'bg-rose-500/15 text-rose-400 border-rose-500/30' :
                      selectedTask.priority === 'HIGH' ? 'bg-amber-500/15 text-amber-400 border-amber-500/30' :
                      'bg-slate-800 text-slate-400 border-slate-700'
                    }`}>
                      {selectedTask.priority === 'URGENT' ? 'عاجل وفوري' : selectedTask.priority === 'HIGH' ? 'أولوية عالية' : 'عادي'}
                    </span>
                  </div>
                  <h2 className="text-base sm:text-lg font-bold text-white leading-snug">
                    {selectedTask.title}
                  </h2>
                </div>
              </div>

              {/* Header Action Buttons */}
              <div className="flex items-center gap-2 flex-wrap w-full sm:w-auto justify-end">
                {selectedTask.deliverable && (
                  <>
                    {/* Word Export */}
                    <button
                      onClick={() => handleWordExport(selectedTask)}
                      className="flex items-center gap-1.5 px-3.5 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-xs font-bold shadow-lg shadow-blue-600/20 transition-all cursor-pointer"
                      title="تحميل كملف Word (.docx) قابل للتعديل"
                    >
                      <Download className="w-3.5 h-3.5" />
                      تصدير Word (.docx)
                    </button>

                    {/* PDF Print Export */}
                    <button
                      onClick={() => handlePdfPrintExport(selectedTask)}
                      className="flex items-center gap-1.5 px-3.5 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-xs font-bold shadow-lg shadow-indigo-600/20 transition-all cursor-pointer"
                      title="طباعة أو تصدير بصيغة PDF"
                    >
                      <Printer className="w-3.5 h-3.5" />
                      طباعة / PDF
                    </button>

                    {/* Copy */}
                    <button
                      onClick={() => handleCopyContent(selectedTask.deliverable!, selectedTask.id)}
                      className="flex items-center gap-1 px-3 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-xl text-xs font-semibold border border-slate-700 transition-colors"
                      title="نسخ محتوى الوثيقة"
                    >
                      {copiedId === selectedTask.id ? (
                        <>
                          <Check className="w-3.5 h-3.5 text-emerald-400" />
                          <span className="text-emerald-400">تم النسخ</span>
                        </>
                      ) : (
                        <>
                          <Copy className="w-3.5 h-3.5" />
                          <span>نسخ</span>
                        </>
                      )}
                    </button>

                    {/* Edit Toggle */}
                    <button
                      onClick={() => setIsEditingDeliverable(!isEditingDeliverable)}
                      className={`flex items-center gap-1 px-3 py-2 rounded-xl text-xs font-semibold border transition-colors ${
                        isEditingDeliverable 
                          ? 'bg-amber-500 text-black border-amber-400 font-bold' 
                          : 'bg-slate-800 hover:bg-slate-700 text-slate-200 border-slate-700'
                      }`}
                      title={isEditingDeliverable ? "إلغاء التعديل والعودة للمعاينة" : "تعديل نص الوثيقة"}
                    >
                      <Edit3 className="w-3.5 h-3.5" />
                      <span>{isEditingDeliverable ? 'معاينة' : 'تعديل'}</span>
                    </button>
                  </>
                )}

                {/* Close Modal */}
                <button
                  onClick={() => setShowPreviewModal(false)}
                  className="p-2 text-slate-400 hover:text-white bg-slate-800 hover:bg-slate-700 rounded-xl transition-all border border-slate-700"
                  title="إغلاق المعاينة"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>
            </div>

            {/* Modal Body */}
            <div className="flex-1 overflow-y-auto p-4 sm:p-8 bg-slate-950/60 space-y-6">
              
              {/* Official Letterhead Header */}
              <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-sm">
                <div className="flex flex-col sm:flex-row items-center justify-between gap-4 pb-4 border-b border-slate-800 text-center sm:text-right">
                  <div className="flex items-center gap-3">
                    <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-blue-600 to-indigo-700 flex items-center justify-center text-white font-bold text-xl shadow-lg">
                      🛡️
                    </div>
                    <div>
                      <h4 className="text-sm font-bold text-white">المؤسسة</h4>
                      <p className="text-xs text-blue-400 font-medium mt-0.5">مخرج الخبير المؤسسي</p>
                    </div>
                  </div>
                  <div className="text-left text-xs text-slate-400 space-y-1">
                    <p><strong className="text-slate-300">رقم الوثيقة:</strong> DOC-{selectedTask.id}-{new Date().getFullYear()}</p>
                    <p><strong className="text-slate-300">تاريخ الإصدار:</strong> {selectedTask.createdAt ? new Date(selectedTask.createdAt).toLocaleDateString('ar-EG') : new Date().toLocaleDateString('ar-EG')}</p>
                    <p><strong className="text-slate-300">الحالة:</strong> <span className="text-amber-400 font-bold">مسودة للمراجعة والاعتماد</span></p>
                  </div>
                </div>
              </div>

              {/* Main Content Area */}
              {isEditingDeliverable ? (
                <div className="space-y-4">
                  <div className="flex items-center justify-between pb-2 border-b border-slate-800 text-xs text-slate-400">
                    <span>محرر نصوص الوثيقة المباشر (Markdown):</span>
                    <button
                      onClick={handleSaveEditedDeliverable}
                      className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl font-bold flex items-center gap-1.5 text-xs shadow-md cursor-pointer"
                    >
                      <Save className="w-3.5 h-3.5" /> حفظ التعديلات
                    </button>
                  </div>
                  <textarea
                    value={editedContent}
                    onChange={(e) => setEditedContent(e.target.value)}
                    rows={20}
                    className="w-full bg-slate-900 border border-slate-700 rounded-2xl p-5 text-white text-xs sm:text-sm font-mono leading-relaxed outline-none focus:border-blue-500 resize-none shadow-inner"
                  />
                </div>
              ) : selectedTask.deliverable ? (
                <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 sm:p-10 shadow-lg">
                  <div className="prose prose-invert max-w-none text-xs sm:text-sm sm:leading-relaxed space-y-4 leading-normal">
                    <ReactMarkdown>{selectedTask.deliverable}</ReactMarkdown>
                  </div>

                  {/* Official Approval & Signatures Block */}
                  <div className="mt-12 pt-8 border-t border-slate-800 grid grid-cols-1 sm:grid-cols-3 gap-6 text-center text-xs">
                    <div className="p-4 rounded-xl bg-slate-950/40 border border-slate-800">
                      <p className="text-slate-500 font-medium mb-1">المعد والمكلف بالصياغة</p>
                      <p className="font-bold text-slate-200">{selectedTask.assignee || 'الذكاء الاصطناعي (المستشار الرقابي)'}</p>
                      <p className="text-[10px] text-emerald-400 mt-2">✓ تم التجهيز والصياغة</p>
                    </div>

                    <div className="p-4 rounded-xl bg-slate-950/40 border border-slate-800">
                      <p className="text-slate-500 font-medium mb-1">التدقيق الفني والامتثال</p>
                      <p className="font-bold text-slate-200">فريق الرقابة والحوكمة</p>
                      <p className="text-[10px] text-blue-400 mt-2">✓ مطابق للوائح والمعايير</p>
                    </div>

                    <div className="p-4 rounded-xl bg-slate-950/40 border border-slate-800">
                      <p className="text-slate-500 font-medium mb-1">الاعتماد النهائي والتصديق</p>
                      <p className="font-bold text-slate-200">مدير إدارة الرقابة والتفتيش</p>
                      <p className="text-[10px] text-indigo-400 mt-2">✓ معتمد للتطبيق الرسمي</p>
                    </div>
                  </div>
                </div>
              ) : (
                <div className="py-20 text-center flex flex-col items-center justify-center text-slate-500 bg-slate-900 border border-slate-800 rounded-3xl p-8">
                  <div className="w-16 h-16 rounded-2xl bg-blue-600/10 border border-blue-500/20 flex items-center justify-center text-blue-400 mb-4">
                    <Sparkles className="w-8 h-8" />
                  </div>
                  <h4 className="text-lg font-bold text-white mb-2">لم يتم توليد وثيقة هذا التكليف بعد</h4>
                  <p className="text-xs text-slate-400 max-w-md mb-6 leading-relaxed">
                    اضغط على الزر أدناه ليقوم المستشار الرقابي الذكي بصياغة دليل إجراءات أو وثيقة رسمية متكاملة وجاهزة فوراً للتصدير بصيغة Word و PDF.
                  </p>
                  <button
                    onClick={handleEnhanceWithAI}
                    disabled={isGeneratingAi}
                    className="px-8 py-3.5 bg-blue-600 hover:bg-blue-500 text-white rounded-2xl text-xs sm:text-sm font-bold shadow-xl shadow-blue-600/20 flex items-center gap-2 disabled:opacity-50 cursor-pointer transition-all"
                  >
                    <Sparkles className="w-4 h-4" />
                    {isGeneratingAi ? 'جاري إعداد وصياغة الدليل...' : 'توليد وإنجاز الدليل فوراً بالذكاء الاصطناعي'}
                  </button>
                </div>
              )}

            </div>

            {/* Bottom AI Prompt Enhancer Bar */}
            {selectedTask.deliverable && (
              <div className="p-4 bg-slate-900 border-t border-slate-800 space-y-2.5">
                
                {/* Quick Suggestion Chips */}
                <div className="flex items-center gap-2 overflow-x-auto pb-1 text-[11px]">
                  <span className="text-slate-500 shrink-0 font-medium">مقترحات سريعة:</span>
                  <button
                    type="button"
                    onClick={() => {
                      setAiPromptInstruction('أضف نموذج استمارة تفتيش ميدانية ومصفوفة مطابقة وجدول مؤشرات');
                    }}
                    className="px-2.5 py-1 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700 whitespace-nowrap"
                  >
                    + استمارة تفتيش ميداني
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      setAiPromptInstruction('وسّع جدول الصلاحيات ومصفوفة المسؤوليات وتوزيع المهام');
                    }}
                    className="px-2.5 py-1 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700 whitespace-nowrap"
                  >
                    + مصفوفة الصلاحيات
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      setAiPromptInstruction('أضف بنود الامتثال والعقوبات والإجراءات التصحيحية');
                    }}
                    className="px-2.5 py-1 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700 whitespace-nowrap"
                  >
                    + الجزاءات والامتثال
                  </button>
                </div>

                {/* Prompt Input */}
                <div className="flex items-center gap-2">
                  <div className="p-2 rounded-xl bg-blue-600/20 text-blue-400 shrink-0">
                    <Sparkles className="w-4 h-4" />
                  </div>
                  <input
                    type="text"
                    value={aiPromptInstruction}
                    onChange={(e) => setAiPromptInstruction(e.target.value)}
                    onKeyDown={(e) => e.key === 'Enter' && handleEnhanceWithAI()}
                    placeholder="اطلب من الذكاء تعديل أو إضافة قسم في الوثيقة (مثال: أضف جدول المتابعة الزمنية)..."
                    className="flex-1 bg-slate-950 border border-slate-800 rounded-xl px-4 py-2.5 text-xs text-white placeholder-slate-500 outline-none focus:border-blue-500"
                  />
                  <button
                    onClick={handleEnhanceWithAI}
                    disabled={isGeneratingAi}
                    className="px-5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-xs font-bold transition-all shadow-md shadow-blue-600/20 disabled:opacity-50 whitespace-nowrap cursor-pointer flex items-center gap-1.5"
                  >
                    {isGeneratingAi ? (
                      <>
                        <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                        <span>جاري التحديث...</span>
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-3.5 h-3.5" />
                        <span>تطوير بالذكاء</span>
                      </>
                    )}
                  </button>
                </div>
              </div>
            )}

          </div>
        </div>
      )}

    </div>
  );
}
